//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GlassFTP.rc
//
#define IDC_BTN_SAVE                    2
#define IDC_BTN_OPEN                    3
#define IDOKALL                         3
#define IDC_BTN_NEW                     4
#define IDC_BTN_DELETE                  5
#define IDM_ABOUTBOX                    0x0010
#define IDM_ABOUT                       0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GLASSFTP_DIALOG             102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDI_FILE_ICON                   133
#define IDI_FORDER_ICON                 135
#define IDI_GET_ICON                    149
#define IDI_PUT_ICON                    150
#define IDB_BITMAP1                     163
#define IDI_SHBF_ICON                   164
#define IDR_MAINMENU                    168
#define IDI_MAIN_ICON                   169
#define IDD_OPEN                        170
#define IDI_PUTALL_ICON                 172
#define IDI_NEWFORDER_ICON              174
#define IDI_DELETE_ICON                 176
#define IDI_PARENT_ICON                 177
#define IDD_FORDERNAME                  178
#define IDD_SERVER                      179
#define IDD_OPTION                      180
#define IDD_MESSAGEBOX                  184
#define IDI_REFRESH                     188
#define IDB_BITMAP2                     195
#define IDI_ICON1                       201
#define IDI_SETPATH                     209
#define IDI_ICON2                       210
#define IDI_GETINFO                     210
#define IDC_LIST_CLIENT                 1000
#define IDC_LIST_SERVER                 1002
#define IDC_EDIT_CLIENT_PATH            1003
#define IDC_BTN_SHBF                    1004
#define IDC_EDIT_SERVER_PATH            1005
#define IDC_BTN_CLIENT_PARENT           1006
#define IDC_BTN_SERVER_PARENT           1007
#define IDC_BTN_CLIENT_NEWFORDER        1008
#define IDC_BTN_SERVER_NEWFORDER        1009
#define IDC_BTN_PUT                     1010
#define IDC_EDIT_ID                     1011
#define IDC_BTN_CLIENT_PATH             1011
#define IDC_EDIT_PASSWORD               1012
#define IDC_BTN_GET                     1013
#define IDC_EDIT_LOG                    1014
#define IDC_BTN_PUTALL                  1015
#define IDC_COMBO_SERVER                1016
#define IDC_EDIT_FORDERNAME             1017
#define IDC_BTN_SERVER_CLOSE            1018
#define IDC_RADIO_FILE_TRANS_ASC        1019
#define IDC_RADIO_FILE_TRANS_BIN        1020
#define IDC_BTN_SERVER_REFRESH          1021
#define IDC_RADIO_FILE_TRANS_AUTO       1022
#define IDC_EDIT_NAME                   1023
#define IDC_BTN_EXIT                    1024
#define IDC_EDIT_FILEPATH               1025
#define IDC_BTN_FILEDLG                 1026
#define IDC_EDIT_INTERVAL               1027
#define IDC_RADIO_SERVERFILECOUNT       1028
#define IDC_RADIO_SERVERFILECOUNT2      1029
#define IDC_EDIT_FILECOUNT              1030
#define IDC_STATIC_MSG                  1031
#define IDC_EDIT_FILEPATH_CONFIG        1031
#define IDC_EDIT_AUTOEXT                1032
#define IDC_COMBO_SERVER_PATH           1033
#define IDC_BTN_FILEDLG_CONFIG          1033
#define IDC_RADIO_BACKUP1               1034
#define IDC_RADIO_BACKUP2               1035
#define IDC_BTN_LOG_CLEAR               1036
#define IDC_EDIT_DIFFPATH               1036
#define IDC_EDIT_BACKUP                 1037
#define IDC_PROGRESS_FTP                1038
#define IDC_BTN_FILEDLG_DIFF            1038
#define IDC_CHECK_CURRENT_SERVER        1039
#define IDC_STATIC_STATUS               1040
#define IDC_STATIC_STATUS_BACKUP        1041
#define IDC_EDIT_IP                     1042
#define IDC_CHECK_CURRENT_SERVER2       1042
#define IDC_PATH_SYNC                   1042
#define IDC_EDIT_PORT                   1043
#define IDC_STATIC_STATUS_CLIENTS       1043
#define IDC_BTN_CLIENT_DELETE           1044
#define IDC_BTN_SERVER_DELETE           1045
#define IDC_EDIT_DEFAULT_PATH           1046
#define IDC_STATIC_STATUS_CLIENTS2      1046
#define IDC_STATIC_STATUS_SERVERS       1046
#define IDC_BTN_CLIENT_REFRESH          1047
#define IDC_EDIT_DEFAULT_PATH_CLIENT    1047
#define IDC_STATIC_TIMER                1048
#define IDC_CHECK_SELECT_CLIENTPATH     1049
#define IDC_BTN_SELECT_CLIENT_PATH      1050
#define IDC_RADIO_MODE_ACTIVE           1051
#define IDC_RADIO_MODE_PASSIVE          1052
#define IDM_OPEN                        32771
#define IDM_CLOSE                       32773
#define IDM_CLOSEALL                    32774
#define IDM_EDITING                     32777
#define IDM_OPTION                      32778
#define IDM_SET_DEFAULT_PATH            32779
#define IDM_EXIT                        32780
#define IDM_EXECUTE                     32782
#define IDM_RENAME                      32783
#define ID_32784                        32784
#define IDM_FILEVIEW_SERVER             32785
#define ID_32786                        32786
#define IDM_DIFF_SERVER                 32787
#define ID_32788                        32788
#define IDM_DIFF_CLIENT                 32789
#define ID_32790                        32790
#define IDM_EXECUTE_SERVER              32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
